blog/blog_api/blog_api/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('api/', include('post.api.urls', namespace='api')),
   # path('api/comments/', include('post.api.urls', namespace='comments-api')),
    ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog_api/post/api/urls.py
from django.urls import path
from .views import (
    PostListAPIView, 
    PostDetailAPIView, 
    PostCreateAPIView,
    CommentDetailAPIView,
    CommentListAPIView,
    CommentCreateAPIView,
    )
#from . import views

app_name = 'post' 

urlpatterns = [
    path('comments/', CommentListAPIView.as_view(), name="comments"),
    path('posts/', PostListAPIView.as_view(), name="post_list"),
    path('posts/create/', PostCreateAPIView.as_view(), name="create"),
    path('comments/<slug:pk>/', CommentDetailAPIView.as_view(), name="thread"),
    path('posts/<slug:pk>/', PostDetailAPIView.as_view(), name="detail"),
    path('posts/<slug:slug>/create_comment', CommentCreateAPIView.as_view(), name="post_comments"),
    ]

blog/blog_api/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns=[
    path('', views.post_list, name="post_list"),
    path('<slug:post>/', views.post_detail, name="post_detail"),
    path('comment/reply/', views.reply_page, name="reply"),
]

blog/blog_api/post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


# post model
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = RichTextUploadingField()
    image = models.ImageField(upload_to='featured_image/%Y/%m/%d/')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    class Meta:
        ordering = ('-publish',)
        
    def __str__(self):
        return self.title

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Custom manager.

    def get_absolute_url(self):
        return reverse('post:post_detail',args=[self.slug])

    # To get comment with parent is none and active is true
    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)

    def get_child_comments(self):
        return self.comments.filter(parent=parent_id).filter(active=True)

    
# Comment model
class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id= obj_id).filter(parent=None)
        return qs


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    objects = CommentManager()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.body

    def get_comments(self):
        return Comment.objects.filter(parent=self).filter(active=True)

    def children(self):
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

blog/blog_api/post/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
    
    # overriding default form setting and adding bootstrap class
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {'placeholder': 'Enter name','class':'form-control'}
        self.fields['email'].widget.attrs = {'placeholder': 'Enter email', 'class':'form-control'}
        self.fields['body'].widget.attrs = {'placeholder': 'Comment here...', 'class':'form-control', 'rows':'5'}

blog/blog_api/post/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView, CreateAPIView
from rest_framework.pagination import (
    LimitOffsetPagination,
    )
from .serializers import (
	PostListSerializer, 
	PostDetailSerializer, 
	PostCreateSerializer, 
	CommentDetailSerializer,
	CommentListSerializer,
	CommentCreateSerializer,
	)
from post.models import Post, Comment


# Comments APIViews
class CommentCreateAPIView(CreateAPIView):
	queryset = Comment.objects.all()
	serializer_class = CommentCreateSerializer

class CommentDetailAPIView(RetrieveAPIView):
	queryset = Comment.objects.all()
	serializer_class = CommentDetailSerializer
	lookup_field = "pk"

class CommentListAPIView(ListAPIView):
	queryset = Comment.objects.all()
	serializer_class = CommentListSerializer


#Post
class PostCreateAPIView(CreateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateSerializer


class PostDetailAPIView(RetrieveAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer


class PostListAPIView(ListAPIView):
	queryset = Post.objects.all()
	serializer_class = PostListSerializer
	pagination_class = LimitOffsetPagination

blog/blog_api/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm


def post_list(request):
    '''
    Returns all published posts.
    '''

    posts = Post.published.all()
    paginator = Paginator(posts, 10)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)

    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
        
    return render(request,'post_list.html',{'posts':posts, page:'pages'})


def post_detail(request, post):
    ''' 
    Returns particular published post by it's slug-name. 
    '''

    post = get_object_or_404(Post,slug=post,status='published')
    # List of active comments for particular post
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm(data=request.POST) 
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect(post.get_absolute_url()+'#'+str(new_comment.id))
        else:
            comment_form = CommentForm()

    return render(request, 'post_detail.html',{'post':post,'comments':comments,'comment_form':comment_form})

# Handling reply, reply view.
def reply_page(request):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post_id = request.POST.get('post_id') 
            parent_id = request.POST.get('parent') 
            post_url = request.POST.get('post_url')
            reply = form.save(commit=False)
            reply.post = Post(id=post_id)
            reply.parent = Comment(id=parent_id)
            reply.children = Comment(id=parent_id)
            reply.save()
            return redirect(post_url+'#'+str(reply.id))
     return redirect("/")

blog/blog_api/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>TestBlog{% block title %}{% endblock title %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- static file -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <!-- javascript add -->
    <script src="{% static 'js/main.js'%}"></script>
    
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
      <a class="navbar-brand" href="/">TestBlog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link1</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link2</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link2</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control mr-0" type="search" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
    
    <main class="container my-3">
        {% block content %}
        {% endblock content %}
    </main>
  <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

blog/blog_api/templates/comment.html
<div class="border-0 border-start border-2 ps-2" id="{{comment.id}}">
        <div class="mt-3">
            <strong>{{comment.name}}</strong> 
            {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
            <small class="text-muted">On {{ comment.created.date }}</small>
        </div>
        <div class="border p-2 rounded">
            <p>{{comment.body}}</p>
            <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
        
            <div id="reply-form-container-{{comment.id}}" style="display:none">
            
                <form method="post" action="{% url 'post:reply' %}" class="mt-3">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{post.id}}">
                    <input type="hidden" name="parent" value="{{comment.id}}">
                    <input type="hidden" name="post_url" value="{{post.get_absolute_url}}">
                    {{comment_form.as_p}}
                    <div>
                        <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        {% for comment in comment.get_comments %}
            {% include 'comment.html' with comment=comment %}
        {% endfor %}
</div>

blog/blog_api/templates/pagination.html
{% if page.has_other_pages %}
  <ul class="pagination mt-3 mb-0">
    {% if page.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

blog/blog_api/templates/post_detail.html
{% extends 'base.html' %}

{% block title %} - {{post.title}} {% endblock title %}
{% block content %}
    <article>
        <figure>
         <img src="{{ post.image.url }}" class="rounded" alt="{{post.title}}">
        </figure>
        <div class="mt-3">
            <h1>{{post.title}}</h1>
            <p class="text-muted">
                Published {{ post.publish.date }} by <strong>{{ post.author }}</strong>
            </p>
        </div>
        <div class="article-body">
            {{ post.body|safe }}
        </div>
    </article>
<hr/>
        <h3>Add Comment</h3>
        <form method="post" action="">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-primary">Comment</button>
        </form>
    
        {% with comments.count as total_comments %}
            <h3 class="mt-5">
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h3>
        {% endwith %}
        {% if not post.comments.all %}
            No comments yet
        
        {% else %}
            {% for comment in post.get_comments %}
                {% include 'comment.html' with comment=comment %}
            {% endfor %}
        {% endif %}
{% endblock content %}

blog/blog_api/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
{% if tag %}
<h2 class="mb-3">Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
<div class="card mb-3">
    <div class="card-body">
        <div class="row g-0">
            <div class="col-md-5">
                <div class="ratio ratio-16x9">
                    <img src="{{ post.image.url }}" class="rounded featured-image-list" alt="{{post.title}}">
                </div>
            </div>
            <div class="col-md-7 ps-md-3 pt-3 pt-md-0 d-flex flex-column">

                <h2 class="card-title h5">
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h2>

                <div class="text-muted">
                    <small>
                        Published {{ post.publish.date }} by <strong>{{ post.author }}</strong>
                    </small>
                </div>


                <p class="card-text mb-auto py-2">{{ post.body|safe|striptags|truncatechars:100 }}</p>


                <div>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary btn-sm">Read more</a>
                </div>

            </div>
        </div>
    </div>
</div>

{% endfor %}

{% include "pagination.html" with page=posts %}

{% endblock content %}